---
slug: tau_manifesto
filename: tau_manifesto
title: The Tau Manifesto
subtitle: No, really, pi is wrong
description: "Given its ubiquity in mathematics, it may surprise you to learn that pi is, in fact, wrong. Building on the work of the mathematical heretics who preceded him, Michael Hartl published The Tau Manifesto on Tau Day (6/28), 2010, thereby launching what has become an international movement for mathematical sanity. Explore the reasons why pi is wrong—that is, why pi is a confusing and unnatural choice for the circle constant—and meet its replacement, tau. Skeptics beware: by the end of the manifesto you may be surprised to find yourself converted to tauism."
author: Michael Hartl
copyright: 2015
uuid: 5dc383dd-c6d3-47db-a97a-486a689a792b
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
