---
chapter:
  word: Chapter
  order: standard     # Use 'reverse' to change 'Chapter 1' to '1 Chapter'
section: Sección
table: Tabla
figure: Figura
fig: Fig
aside: Box
listing: Listing
equation: Ecuacón
eq: Eq
frontmatter: Frontmatter
contents: Contents
